### ISSUE TITLE
Host the webapp?

### ISSUE THREAD

**Issue by bakkot** [str4d/wage#18]
It seems like this could be hosted on Github Pages, which would let people do `age`-based encryption/decryption without needing any setup at all. Are there plans to do so?

**Comment by str4d** [comment]
I'm actually already hosting the webapp 😄 It gets deployed to a not-so-secret domain, but I haven't publicised it yet because the webapp part is still a work in progress.

**Comment by bakkot** [comment]
Neat! I look forward to its less-secret deployment someday.

**Comment by str4d** [comment]
I've finally reached the point where I'm happy to move `wage` into beta!

https://rage-encry.pt/

**Comment by bakkot** [comment]
Nice! Maybe link it as the website in the repository settings?

**Comment by str4d** [comment]
Already done :)
